stages:
  - deploy

.deploy_template:
  image: alpine/k8s:1.30.14
  before_script:
    - apk add --no-cache gettext
    - kubectl config set-cluster rancher --server="$K8S_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials deploy --token="$DEPLOY_TOKEN"
    - kubectl config set-context "$KUBE_CONTEXT" --cluster=rancher --user=deploy
    - kubectl config use-context "$KUBE_CONTEXT"
  script:
    - sh scripts/deploy-app.sh "$ENV" ecargo-analytics

.hml_deploy:
  extends: .deploy_template
  variables:
    K8S_URL: "https://rks.loginlogistica.com.br/k8s/clusters/c-6htg4"
    KUBE_CONTEXT: "cluster-tvv-stg-rke2"
    DEPLOY_TOKEN: "$TOKEN_STG"
    ENV: "hml"

.prd_deploy:
  extends: .deploy_template
  variables:
    K8S_URL: "https://rks.loginlogistica.com.br/k8s/clusters/c-lsb4h"
    KUBE_CONTEXT: "cluster-tvv-prd"
    DEPLOY_TOKEN: "$TOKEN"
    ENV: "prd"

deploy_ecargo_analytics_hml:
  extends: .hml_deploy
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "ecargo-analytics-hml"'

deploy_ecargo_analytics_prd:
  extends: .prd_deploy
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "ecargo-analytics-prd"'
